# Generated by Django 6.0.3 on 2026-04-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='last_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
