# Generated by Django 6.0.3 on 2026-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='description',
            new_name='store_description',
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_phone',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
