# Generated by Django 6.0.3 on 2026-05-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_rename_description_vendor_store_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store_phone',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
