# Generated by Django 6.0.3 on 2026-05-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_store_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='store_phone',
            field=models.IntegerField(null=True),
        ),
    ]
