# Generated by Django 6.0.3 on 2026-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
