# Generated by Django 6.0.3 on 2026-05-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_failure_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
